## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: '%' # Main Prefix 
token: 'NzU2MjQxMzgwMzA4NjgwNzQ0.X2O-qw.E5Np6b8XqWcWlBs_kFxFjYbtzGw' # Token of your bot
status: '' # ur bot status
## Join Support Guild: https://discord.gg/6KYRXQC  ##
