## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: "-" # Main Prefix
token: "NzY0NTU0NDIzMzUxMTE1Nzc3.X4H8yw.V9rNfF1gpuC5qaUHbDBdsoP7oCI" # Token of your bot
status: "test" # ur bot status
## Join Support Guild: https://discord.gg/devs  ##
